### ISSUE TITLE
Upload Inicial 

### ISSUE THREAD

**Issue by jonatascaraujo** [jonatascaraujo/desafiosDeProgramacao#1]
### Descrição
Fazer o upload inicial

### Problema
 102:Mochila binaria ecológica 

### Tasks
- [x] Código
- [x] Exemplo de entrada
- [x] Exemplo de saída
- [x] Descrição do problema
